### ISSUE TITLE
Edit: Try to support copying

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/autosurvive#6]
Might be possible somehow, pasting seems to work mysteriously

**Comment by randomnine** [comment]
Paste works on the Flash target because it uses an invisible TextField with focus to receive input. TextField objects with focus automatically handle copy/paste. Unfortunately, they also block other code from receiving clipboard keypresses or events (Event.CUT, Event.COPY, Event.PASTE).

Handling the clipboard correctly in Flash would mean no longer using a TextField to catch input and managing our own input buffer from keypresses instead.

Clipboard events are thrown by the InteractiveObject with focus, so can be handled by (for example) setting "stage.focus = stage" in KEY_DOWN events, catching Event.CUT/Event.COPY/Event.PASTE on the stage, and using Clipboard.generalClipboard from within the event handlers (as access to the system clipboard is otherwise restricted by Flash).

ref http://help.adobe.com/en_US/as3/dev/WS2F6A31B9-1AE6-4b23-9C12-57A33F4F0516.html

**Comment by TerryCavanagh** [comment]
Ah, that makes sense - ok, making our own input buffer shouldn't be a big deal! I'll try to remove the TextField code from haxegon completely tomorrow.

**Comment by TerryCavanagh** [comment]
Came across this addon which allows clipboard access on native targets, might be useful later

http://community.openfl.org/t/accessing-the-clipboard/574/2

**Comment by TerryCavanagh** [comment]
Still a few bugs with this; gonna try and fix them before I close it:

- Pasting drops mouse focus

- Copy should only happen when the highlight selection changes, right now it happens everyframe

**Comment by TerryCavanagh** [comment]
Pfft, ok, can't figure out the mouse focus one. Will do for now!
