### ISSUE TITLE
Unread emails aren't being counted correctly

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/autosurvive#90]
It's very weird, I can't figure it out right now :/

**Comment by TerryCavanagh** [comment]
(you can replicate it by just reading your emails, and exiting to the pda menu again)

**Comment by randomnine** [comment]
okay! lemme take a look

**Comment by randomnine** [comment]
Looks like we have two separate ways of indexing emails in various arrays:
1) the asset index of the email in the list of all possible email.txts, used for Email.text, Email.name, Email.subject and Email.author
2) the index of the email in our current inbox, used for Email.list and Email.read

The two emails loaded on day 1 have global indices 4 and 5 but list/read indices of 0 and 1. However, the PDA code was accessing Email.read[] using the email's asset index instead of its inbox index.

When you do an out-of-bounds array access on a HaXe array it expands the array and fills the new space with default values (in this case 0s), so checking Email.read[4] and Email.read[5] would expand the array to give it 6 elements ([0,0,0,0,0,0]). Reading them would then set their global indices as read ([0,0,0,0,1,1]). Email.unread() would then access this array and show four unread emails.

**Comment by TerryCavanagh** [comment]
Whoops! Also, yep, that explains why I couldn't figure it out. Very mysterious!
